Python - numpy.

In [1]:
import numpy
import numpy as np

ndarray의 모든 원소는 같은 자료형이어야.

In [8]:
arr = np.array([1, 'A', True])
arr

array(['1', 'A', 'True'], dtype='<U21')

In [10]:
type(arr[2])

numpy.str_

In [16]:
print(arr.size)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

3
1
(3,)
<U21


In [17]:
data1 = [6, 7.6, 8, 0, 1, 2]
arr1 = np.array(data1, dtype='int')
arr1

array([6, 7, 8, 0, 1, 2])

In [18]:
print(arr1.astype(bool))

[ True  True  True False  True  True]


In [20]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr3 = arr2.reshape(4,2)
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
arr4 = arr2.reshape(2,2,2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
data3 = [[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]
arr3 = np.array(data3)
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
print(arr3.shape)

(2, 2, 3)


다음은 여러가지 배열의 생성 방법임.

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
np.empty_like(arr2)

array([[              0,    523986012155,    489626271845,
           493921239151],
       [   227633266728,              41, 105553163813328,
             1627472944]])

In [34]:
np.empty((2,3,3))

array([[[0.00000000e+000, 2.35541533e-312, 2.41907520e-312],
        [2.14321575e-312, 2.46151512e-312, 2.31297541e-312],
        [2.35541533e-312, 2.05833592e-312, 2.22809558e-312]],

       [[2.56761491e-312, 2.48273508e-312, 2.05833592e-312],
        [2.05833592e-312, 2.29175545e-312, 2.07955588e-312],
        [2.14321575e-312, 0.00000000e+000, 0.00000000e+000]]])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [37]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [39]:
np.logspace(0, 4, 4, endpoint=False) # 10^0, 10^1, 10^2, 10^3

array([   1.,   10.,  100., 1000.])

In [40]:
np.logspace(0, 4, 4, endpoint=True) # 10^0, 10^(4/3), 10^(8/3), 10^(12/3)

array([1.00000000e+00, 2.15443469e+01, 4.64158883e+02, 1.00000000e+04])

난수는 다음과 같이 생성할 수 있음.

In [41]:
np.random.seed(100)

In [42]:
np.random.rand(10) # From Uniform Distribution.

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [43]:
np.random.randn(10) # From Normal Distribution: N(0, 1)

array([-0.18949583,  0.25500144, -0.45802699,  0.43516349, -0.58359505,
        0.81684707,  0.67272081, -0.10441114, -0.53128038,  1.02973269])

In [44]:
np.random.randn(3, 5) 

array([[-0.43813562, -1.11831825,  1.61898166,  1.54160517, -0.25187914],
       [-0.84243574,  0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  , -0.75635231]])

In [45]:
np.random.normal(3, 5, 10) # Normal Distribution with mean 3, sigma 5, size 10.

array([ 7.08227006,  6.75222381,  0.72026536,  8.94811134, -5.45308413,
       -3.78199524, -3.16217257,  0.27780419, -0.34085868,  3.03657282])

다음은 인덱싱과 슬라이싱.

In [46]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr2[0]

array([1, 2, 3])

In [48]:
arr2[0,1]

2

In [49]:
arr2[0][1]

2

In [50]:
arr2[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [51]:
arr2[:, 1]

array([2, 5, 8])

In [52]:
arr2[0, :]

array([1, 2, 3])

팬시 인덱싱은 아래처럼 진행.

In [53]:
arr2[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [54]:
arr2[[0,2],[1,2]]

array([2, 9])

불리언 인덱싱도 가능.

In [55]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
b_arr = np.array([[False, True, False], [True, False, True], [False, True, False]])
b_arr

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [57]:
print(arr[b_arr])

[2 4 6 8]


In [62]:
names = np.array(['Bob', 'Joe', 'Mill', 'Bob', 'Mill', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Mill', 'Bob', 'Mill', 'Joe', 'Joe'], dtype='<U4')

In [63]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [64]:
data = np.random.randn(7, 4)
data

array([[ 0.36609323, -0.33177714, -0.68921798,  2.03460756],
       [-0.55071441,  0.75045333, -1.30699234,  0.58057334],
       [-1.10452309,  0.69012147,  0.68689007, -1.56668753],
       [ 0.90497412,  0.7788224 ,  0.42823287,  0.10887199],
       [ 0.02828363, -0.57882582, -1.1994512 , -1.70595201],
       [ 0.36916396,  1.87657343, -0.37690335,  1.83193608],
       [ 0.00301743, -0.07602347,  0.00395759, -0.18501411]])

In [65]:
data[names == 'Bob']

array([[ 0.36609323, -0.33177714, -0.68921798,  2.03460756],
       [ 0.90497412,  0.7788224 ,  0.42823287,  0.10887199]])

In [66]:
data[names == 'Bob', 2:]

array([[-0.68921798,  2.03460756],
       [ 0.42823287,  0.10887199]])

In [67]:
data[data < 0]

array([-0.33177714, -0.68921798, -0.55071441, -1.30699234, -1.10452309,
       -1.56668753, -0.57882582, -1.1994512 , -1.70595201, -0.37690335,
       -0.07602347, -0.18501411])

In [68]:
data[data < 0] = 0
data

array([[0.36609323, 0.        , 0.        , 2.03460756],
       [0.        , 0.75045333, 0.        , 0.58057334],
       [0.        , 0.69012147, 0.68689007, 0.        ],
       [0.90497412, 0.7788224 , 0.42823287, 0.10887199],
       [0.02828363, 0.        , 0.        , 0.        ],
       [0.36916396, 1.87657343, 0.        , 1.83193608],
       [0.00301743, 0.        , 0.00395759, 0.        ]])

1/9

In [2]:
a = [0,1,2,3,4,5]

In [4]:
np.array(a) * 2

array([ 0,  2,  4,  6,  8, 10])

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([-1,3,-4])
d = np.array([4.5, 6.3, 7.8, 4.4, 3])

In [6]:
print(np.abs(c))
print(np.fabs(c))
print(np.sqrt(b))
print(np.square(a))

[1 3 4]
[1. 3. 4.]
[2.         2.23606798 2.44948974]
[1 4 9]


In [7]:
print(np.exp(a))
print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.sign(c))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[-1  1 -1]


In [8]:
print(np.modf(d)[0])
print(np.modf(d)[1])

[0.5 0.3 0.8 0.4 0. ]
[4. 6. 7. 4. 3.]


In [9]:
arr = np.array([1,2,3,4])

In [10]:
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))

4
1
0


In [11]:
print(arr.mean())
print(arr.std())
print(arr.var())

2.5
1.118033988749895
1.25


In [12]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(np.sum(arr2, axis=0))

[5 7 9]


In [14]:
print(arr2.sum(axis=1))

[ 6 15]


In [15]:
arr = np.random.randn(20)

In [16]:
arr

array([-0.23435539,  0.49897267,  0.71474198,  0.56463797,  0.14212076,
       -1.23968961,  0.43590463,  0.29854283, -0.91552632, -1.06887125,
       -0.07895875,  1.60362058,  1.5822736 ,  1.00168799, -1.69315608,
        0.2650515 ,  0.15751961, -1.28586859,  0.25966347, -2.28512737])

In [17]:
arr > 0

array([False,  True,  True,  True,  True, False,  True,  True, False,
       False, False,  True,  True,  True, False,  True,  True, False,
        True, False])

In [18]:
(arr > 0).sum()

12

In [19]:
a = np.array([0, 1, 2, np.nan, 4, np.inf, np.NINF, np.PINF])
a

array([  0.,   1.,   2.,  nan,   4.,  inf, -inf,  inf])

In [20]:
print(np.isnan(a))
print(np.isinf(a))
print(np.isfinite(a))

[False False False  True False False False False]
[False False False False False  True  True  True]
[ True  True  True False  True False False False]


In [21]:
a = np.array([4,2,6,3,2,7,8])
np.where(a<5)

(array([0, 1, 3, 4]),)

In [22]:
np.where(a<5, 0, a) # make 0 if less than 5, a if not.

array([0, 0, 6, 0, 0, 7, 8])

In [23]:
p = "P"
q = np.array(["P", "Q"])
r = np.array(["R", "S"])

In [24]:
print(p in q)
print(p in r)
print(p not in q)
print(p not in r)

True
False
False
True


배열 전치와 재형성.

In [25]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr1 = arr.reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr.resize((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
arr2 = arr.T
arr2

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [31]:
arr1.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [32]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
a = np.array([1,2,3,4])
a2 = a[:, np.newaxis]
print(a2)

[[1]
 [2]
 [3]
 [4]]


In [35]:
a3 = a[np.newaxis, :]
print(a3)

[[1 2 3 4]]


In [36]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [37]:
np.tile(arr, 2)

array([0, 1, 2, 0, 1, 2])

In [38]:
np.tile(arr, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

배열 결합과 분리: concatenate, vstack, hstack, dstack을 사용.

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([[0,1,2],[3,4,5]])
d = np.array([[6,7,8],[9,10,11]])

In [40]:
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [41]:
print(np.concatenate((a,b))) # array has one row, then they are flattened.

[1 2 3 4 5 6]


In [42]:
print(np.concatenate((c,d)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
print(np.concatenate((c,d), axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
print(np.concatenate((c,d), axis=1))

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [45]:
np.dstack((c,d))

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [46]:
e = np.array([[[0,1,2], [3,4,5]]])
f = np.array([[[6,7,8], [9,10,11]]])

print(e)
print(f)

[[[0 1 2]
  [3 4 5]]]
[[[ 6  7  8]
  [ 9 10 11]]]


In [47]:
print(e.shape, f.shape)

(1, 2, 3) (1, 2, 3)


In [48]:
print(np.dstack((e,f)))

[[[ 0  1  2  6  7  8]
  [ 3  4  5  9 10 11]]]


배열 분리: split, hsplit, vsplit 사용.

In [50]:
a = np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
np.split(a, 4) # axis=0

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [52]:
np.split(a, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [53]:
np.split(a, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [54]:
np.hsplit(a, 3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [55]:
np.vsplit(a, 4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

배열 변경: append, insert, delete 사용.

In [57]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
print(a) ; print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [58]:
np.append(a, b) # make 1-dimensional.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [59]:
print(np.append(a, b, axis=0))
print(np.append(a, b, axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [61]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
np.insert(a, 1, 999) # insert 999 in 1st index.

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [63]:
print(np.insert(a, 1, 999, axis=0))
print(np.insert(a, 1, 999, axis=1))

[[  1   2   3]
 [999 999 999]
 [  4   5   6]
 [  7   8   9]]
[[  1 999   2   3]
 [  4 999   5   6]
 [  7 999   8   9]]


In [64]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
np.delete(a, 1) # delete 1st index.

array([1, 3, 4, 5, 6, 7, 8, 9])

In [66]:
print(np.delete(a, 1, axis=0))
print(np.delete(a, 1, axis=1))

[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [67]:
a = np.array([2,1,3,4])
a

array([2, 1, 3, 4])

In [68]:
np.sort(a)

array([1, 2, 3, 4])

In [69]:
a = np.array([[4,3,5], [1,2,1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [70]:
np.sort(a)

array([[3, 4, 5],
       [1, 1, 2]])

In [71]:
np.sort(a, axis=0)

array([[1, 2, 1],
       [4, 3, 5]])

In [72]:
np.sort(a, axis=1)

array([[3, 4, 5],
       [1, 1, 2]])

In [73]:
a = np.array([[4,3,5], [1,4,1]])
print(a)

[[4 3 5]
 [1 4 1]]


In [74]:
np.sort(a, axis=0)

array([[1, 3, 1],
       [4, 4, 5]])

In [76]:
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [77]:
a[j]

array([1, 2, 3, 4])

선형대수: diag, dot, trace, linalg.det, linalg.solve, linalg.inv를 사용

In [78]:
a = np.diag([1,1])
b = np.array([[1,2], [3,4]])

In [79]:
print(a) ; print(b)

[[1 0]
 [0 1]]
[[1 2]
 [3 4]]


In [81]:
print(a * b) ; print(np.multiply(a,b))

[[1 0]
 [0 4]]
[[1 0]
 [0 4]]


In [82]:
print(np.dot(a,b))

[[1 2]
 [3 4]]


In [85]:
print(np.linalg.inv(a))

[[1. 0.]
 [0. 1.]]


In [86]:
print(np.linalg.inv(b))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [91]:
print(np.dot(b, np.linalg.inv(b)))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [92]:
print(np.linalg.det(b))

-2.0000000000000004


In [93]:
# 4x + 3y = 23
# 3x + 2y = 16

a = np.array([[4,3], [3,2]])
b = np.array([23, 16])
x = np.linalg.solve(a, b)
print(x)

[2. 5.]


브로드캐스팅(broadcasting, 서로 다른 크기를 가진 두 배열의 사칙연산)

In [94]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [95]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [96]:
x + y

array([1, 2, 3, 4, 5])

In [98]:
x + np.array([1]) # this is the broadcasting.

array([1, 2, 3, 4, 5])

In [99]:
a = np.tile(np.arange(0, 40, 10), (3,1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [100]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [101]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [103]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

In [104]:
a = a.reshape(4, 1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [105]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [106]:
arr1 = np.array([[2,3,4], [6,7,8]])
arr3 = np.array([100, 200, 300])
print(arr1.shape, arr3.shape)

(2, 3) (3,)


In [107]:
arr1 + arr3

array([[102, 203, 304],
       [106, 207, 308]])